//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitpymes.Core.Validations.Abstractions {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kitpymes.Core.Validations.Abstractions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directory path not found.
        /// </summary>
        public static string MsgDirectory {
            get {
                return ResourceManager.GetString("MsgDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} not found.
        /// </summary>
        public static string MsgDirectoryWithFieldName {
            get {
                return ResourceManager.GetString("MsgDirectoryWithFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directory path {0} not found.
        /// </summary>
        public static string MsgDirectoryWithValue {
            get {
                return ResourceManager.GetString("MsgDirectoryWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directory path {0} for field {1} not found.
        /// </summary>
        public static string MsgDirectoryWithValueAndFieldName {
            get {
                return ResourceManager.GetString("MsgDirectoryWithValueAndFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email address has an invalid format.
        /// </summary>
        public static string MsgEmail {
            get {
                return ResourceManager.GetString("MsgEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} has an invalid format.
        /// </summary>
        public static string MsgEmailWithFieldName {
            get {
                return ResourceManager.GetString("MsgEmailWithFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email address {0} has an invalid format.
        /// </summary>
        public static string MsgEmailWithValue {
            get {
                return ResourceManager.GetString("MsgEmailWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email address {0} for field {1} has an invalid format.
        /// </summary>
        public static string MsgEmailWithValueAndFieldName {
            get {
                return ResourceManager.GetString("MsgEmailWithValueAndFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comparator fields do not match.
        /// </summary>
        public static string MsgEqual {
            get {
                return ResourceManager.GetString("MsgEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compared {0} do not match.
        /// </summary>
        public static string MsgEqualFieldName {
            get {
                return ResourceManager.GetString("MsgEqualFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} does not match field {1}.
        /// </summary>
        public static string MsgEqualFieldsName {
            get {
                return ResourceManager.GetString("MsgEqualFieldsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File path extension not found.
        /// </summary>
        public static string MsgExtension {
            get {
                return ResourceManager.GetString("MsgExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} not found.
        /// </summary>
        public static string MsgExtensionWithFieldName {
            get {
                return ResourceManager.GetString("MsgExtensionWithFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File path extension {0} not found.
        /// </summary>
        public static string MsgExtensionWithValue {
            get {
                return ResourceManager.GetString("MsgExtensionWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File path extension {0} for field {1} not found.
        /// </summary>
        public static string MsgExtensionWithValueAndFieldName {
            get {
                return ResourceManager.GetString("MsgExtensionWithValueAndFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File path not found.
        /// </summary>
        public static string MsgFile {
            get {
                return ResourceManager.GetString("MsgFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} not found.
        /// </summary>
        public static string MsgFileWithFieldName {
            get {
                return ResourceManager.GetString("MsgFileWithFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File path {0} not found.
        /// </summary>
        public static string MsgFileWithValue {
            get {
                return ResourceManager.GetString("MsgFileWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File path {0} for field {1} not found.
        /// </summary>
        public static string MsgFileWithValueAndFieldName {
            get {
                return ResourceManager.GetString("MsgFileWithValueAndFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred, try the operation again or contact your system administrator.
        /// </summary>
        public static string MsgFriendlyUnexpectedError {
            get {
                return ResourceManager.GetString("MsgFriendlyUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field has an invalid format.
        /// </summary>
        public static string MsgInvalidFormat {
            get {
                return ResourceManager.GetString("MsgInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} has an invalid format.
        /// </summary>
        public static string MsgInvalidFormatFieldName {
            get {
                return ResourceManager.GetString("MsgInvalidFormatFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field must be less than {0}.
        /// </summary>
        public static string MsgMax {
            get {
                return ResourceManager.GetString("MsgMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} must be less than {1}.
        /// </summary>
        public static string MsgMaxFieldName {
            get {
                return ResourceManager.GetString("MsgMaxFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field must be more than {0}.
        /// </summary>
        public static string MsgMin {
            get {
                return ResourceManager.GetString("MsgMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} must be more than {1}.
        /// </summary>
        public static string MsgMinFieldName {
            get {
                return ResourceManager.GetString("MsgMinFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name has an invalid format.
        /// </summary>
        public static string MsgName {
            get {
                return ResourceManager.GetString("MsgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} has an invalid format.
        /// </summary>
        public static string MsgNameWithFieldName {
            get {
                return ResourceManager.GetString("MsgNameWithFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name {0} has an invalid format.
        /// </summary>
        public static string MsgNameWithValue {
            get {
                return ResourceManager.GetString("MsgNameWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name {0} for field {1} has an invalid format.
        /// </summary>
        public static string MsgNameWithValueAndFieldName {
            get {
                return ResourceManager.GetString("MsgNameWithValueAndFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain a minimum {0} characters.
        /// </summary>
        public static string MsgPassword {
            get {
                return ResourceManager.GetString("MsgPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} must contain a minimum {1} characters.
        /// </summary>
        public static string MsgPasswordWithFieldName {
            get {
                return ResourceManager.GetString("MsgPasswordWithFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field must contain between {0} and {1}.
        /// </summary>
        public static string MsgRange {
            get {
                return ResourceManager.GetString("MsgRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} must contain between {1} and {2}.
        /// </summary>
        public static string MsgRangeFieldName {
            get {
                return ResourceManager.GetString("MsgRangeFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field is a mandatory.
        /// </summary>
        public static string MsgRequired {
            get {
                return ResourceManager.GetString("MsgRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} is a mandatory.
        /// </summary>
        public static string MsgRequiredFieldName {
            get {
                return ResourceManager.GetString("MsgRequiredFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subdomain has an invalid format.
        /// </summary>
        public static string MsgSubdomain {
            get {
                return ResourceManager.GetString("MsgSubdomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field {0} has an invalid format.
        /// </summary>
        public static string MsgSubdomainWithFieldName {
            get {
                return ResourceManager.GetString("MsgSubdomainWithFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subdomain {0} has an invalid format.
        /// </summary>
        public static string MsgSubdomainWithValue {
            get {
                return ResourceManager.GetString("MsgSubdomainWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subdomain {0} for field {1} has an invalid format.
        /// </summary>
        public static string MsgSubdomainWithValueAndFieldName {
            get {
                return ResourceManager.GetString("MsgSubdomainWithValueAndFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unauthorized access.
        /// </summary>
        public static string MsgUnauthorizedAccess {
            get {
                return ResourceManager.GetString("MsgUnauthorizedAccess", resourceCulture);
            }
        }
    }
}
